package com.example.entity.system;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.ORDER_DATE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date orderDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.STATUS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.ORDER_ID
     *
     * @return the value of SYSTEM.ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.ORDER_ID
     *
     * @param orderId the value for SYSTEM.ORDERS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.CUSTOMER_ID
     *
     * @return the value of SYSTEM.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.CUSTOMER_ID
     *
     * @param customerId the value for SYSTEM.ORDERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.ORDER_DATE
     *
     * @return the value of SYSTEM.ORDERS.ORDER_DATE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.ORDER_DATE
     *
     * @param orderDate the value for SYSTEM.ORDERS.ORDER_DATE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.STATUS
     *
     * @return the value of SYSTEM.ORDERS.STATUS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.STATUS
     *
     * @param status the value for SYSTEM.ORDERS.STATUS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.CREATED_AT
     *
     * @return the value of SYSTEM.ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.CREATED_AT
     *
     * @param createdAt the value for SYSTEM.ORDERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDERS.UPDATED_AT
     *
     * @return the value of SYSTEM.ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDERS.UPDATED_AT
     *
     * @param updatedAt the value for SYSTEM.ORDERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}