package com.example.entity.system;

import java.math.BigDecimal;
import java.util.Date;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.PRODUCT_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Integer stockQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.PRODUCT_ID
     *
     * @return the value of SYSTEM.PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.PRODUCT_ID
     *
     * @param productId the value for SYSTEM.PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.PRODUCT_NAME
     *
     * @return the value of SYSTEM.PRODUCTS.PRODUCT_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.PRODUCT_NAME
     *
     * @param productName the value for SYSTEM.PRODUCTS.PRODUCT_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.UNIT_PRICE
     *
     * @return the value of SYSTEM.PRODUCTS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.UNIT_PRICE
     *
     * @param unitPrice the value for SYSTEM.PRODUCTS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.STOCK_QUANTITY
     *
     * @return the value of SYSTEM.PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Integer getStockQuantity() {
        return stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.STOCK_QUANTITY
     *
     * @param stockQuantity the value for SYSTEM.PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.CREATED_AT
     *
     * @return the value of SYSTEM.PRODUCTS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.CREATED_AT
     *
     * @param createdAt the value for SYSTEM.PRODUCTS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.PRODUCTS.UPDATED_AT
     *
     * @return the value of SYSTEM.PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.PRODUCTS.UPDATED_AT
     *
     * @param updatedAt the value for SYSTEM.PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}