package com.example.entity.public;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TestTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public TestTblExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCol1IsNull() {
            addCriterion("col_1 is null");
            return (Criteria) this;
        }

        public Criteria andCol1IsNotNull() {
            addCriterion("col_1 is not null");
            return (Criteria) this;
        }

        public Criteria andCol1EqualTo(String value) {
            addCriterion("col_1 =", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotEqualTo(String value) {
            addCriterion("col_1 <>", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1GreaterThan(String value) {
            addCriterion("col_1 >", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1GreaterThanOrEqualTo(String value) {
            addCriterion("col_1 >=", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1LessThan(String value) {
            addCriterion("col_1 <", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1LessThanOrEqualTo(String value) {
            addCriterion("col_1 <=", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1Like(String value) {
            addCriterion("col_1 like", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotLike(String value) {
            addCriterion("col_1 not like", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1In(List<String> values) {
            addCriterion("col_1 in", values, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotIn(List<String> values) {
            addCriterion("col_1 not in", values, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1Between(String value1, String value2) {
            addCriterion("col_1 between", value1, value2, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotBetween(String value1, String value2) {
            addCriterion("col_1 not between", value1, value2, "col1");
            return (Criteria) this;
        }

        public Criteria andCol2IsNull() {
            addCriterion("col_2 is null");
            return (Criteria) this;
        }

        public Criteria andCol2IsNotNull() {
            addCriterion("col_2 is not null");
            return (Criteria) this;
        }

        public Criteria andCol2EqualTo(String value) {
            addCriterion("col_2 =", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotEqualTo(String value) {
            addCriterion("col_2 <>", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2GreaterThan(String value) {
            addCriterion("col_2 >", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2GreaterThanOrEqualTo(String value) {
            addCriterion("col_2 >=", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2LessThan(String value) {
            addCriterion("col_2 <", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2LessThanOrEqualTo(String value) {
            addCriterion("col_2 <=", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2Like(String value) {
            addCriterion("col_2 like", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotLike(String value) {
            addCriterion("col_2 not like", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2In(List<String> values) {
            addCriterion("col_2 in", values, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotIn(List<String> values) {
            addCriterion("col_2 not in", values, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2Between(String value1, String value2) {
            addCriterion("col_2 between", value1, value2, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotBetween(String value1, String value2) {
            addCriterion("col_2 not between", value1, value2, "col2");
            return (Criteria) this;
        }

        public Criteria andCol3IsNull() {
            addCriterion("col_3 is null");
            return (Criteria) this;
        }

        public Criteria andCol3IsNotNull() {
            addCriterion("col_3 is not null");
            return (Criteria) this;
        }

        public Criteria andCol3EqualTo(String value) {
            addCriterion("col_3 =", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotEqualTo(String value) {
            addCriterion("col_3 <>", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3GreaterThan(String value) {
            addCriterion("col_3 >", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3GreaterThanOrEqualTo(String value) {
            addCriterion("col_3 >=", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3LessThan(String value) {
            addCriterion("col_3 <", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3LessThanOrEqualTo(String value) {
            addCriterion("col_3 <=", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3Like(String value) {
            addCriterion("col_3 like", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotLike(String value) {
            addCriterion("col_3 not like", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3In(List<String> values) {
            addCriterion("col_3 in", values, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotIn(List<String> values) {
            addCriterion("col_3 not in", values, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3Between(String value1, String value2) {
            addCriterion("col_3 between", value1, value2, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotBetween(String value1, String value2) {
            addCriterion("col_3 not between", value1, value2, "col3");
            return (Criteria) this;
        }

        public Criteria andCol4IsNull() {
            addCriterion("col_4 is null");
            return (Criteria) this;
        }

        public Criteria andCol4IsNotNull() {
            addCriterion("col_4 is not null");
            return (Criteria) this;
        }

        public Criteria andCol4EqualTo(Long value) {
            addCriterion("col_4 =", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotEqualTo(Long value) {
            addCriterion("col_4 <>", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4GreaterThan(Long value) {
            addCriterion("col_4 >", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4GreaterThanOrEqualTo(Long value) {
            addCriterion("col_4 >=", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4LessThan(Long value) {
            addCriterion("col_4 <", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4LessThanOrEqualTo(Long value) {
            addCriterion("col_4 <=", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4In(List<Long> values) {
            addCriterion("col_4 in", values, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotIn(List<Long> values) {
            addCriterion("col_4 not in", values, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4Between(Long value1, Long value2) {
            addCriterion("col_4 between", value1, value2, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotBetween(Long value1, Long value2) {
            addCriterion("col_4 not between", value1, value2, "col4");
            return (Criteria) this;
        }

        public Criteria andCol5IsNull() {
            addCriterion("col_5 is null");
            return (Criteria) this;
        }

        public Criteria andCol5IsNotNull() {
            addCriterion("col_5 is not null");
            return (Criteria) this;
        }

        public Criteria andCol5EqualTo(BigDecimal value) {
            addCriterion("col_5 =", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotEqualTo(BigDecimal value) {
            addCriterion("col_5 <>", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5GreaterThan(BigDecimal value) {
            addCriterion("col_5 >", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("col_5 >=", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5LessThan(BigDecimal value) {
            addCriterion("col_5 <", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("col_5 <=", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5In(List<BigDecimal> values) {
            addCriterion("col_5 in", values, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotIn(List<BigDecimal> values) {
            addCriterion("col_5 not in", values, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("col_5 between", value1, value2, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("col_5 not between", value1, value2, "col5");
            return (Criteria) this;
        }

        public Criteria andCol6IsNull() {
            addCriterion("col_6 is null");
            return (Criteria) this;
        }

        public Criteria andCol6IsNotNull() {
            addCriterion("col_6 is not null");
            return (Criteria) this;
        }

        public Criteria andCol6EqualTo(Date value) {
            addCriterion("col_6 =", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotEqualTo(Date value) {
            addCriterion("col_6 <>", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6GreaterThan(Date value) {
            addCriterion("col_6 >", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6GreaterThanOrEqualTo(Date value) {
            addCriterion("col_6 >=", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6LessThan(Date value) {
            addCriterion("col_6 <", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6LessThanOrEqualTo(Date value) {
            addCriterion("col_6 <=", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6In(List<Date> values) {
            addCriterion("col_6 in", values, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotIn(List<Date> values) {
            addCriterion("col_6 not in", values, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6Between(Date value1, Date value2) {
            addCriterion("col_6 between", value1, value2, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotBetween(Date value1, Date value2) {
            addCriterion("col_6 not between", value1, value2, "col6");
            return (Criteria) this;
        }

        public Criteria andCol7IsNull() {
            addCriterion("col_7 is null");
            return (Criteria) this;
        }

        public Criteria andCol7IsNotNull() {
            addCriterion("col_7 is not null");
            return (Criteria) this;
        }

        public Criteria andCol7EqualTo(Date value) {
            addCriterion("col_7 =", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotEqualTo(Date value) {
            addCriterion("col_7 <>", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7GreaterThan(Date value) {
            addCriterion("col_7 >", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7GreaterThanOrEqualTo(Date value) {
            addCriterion("col_7 >=", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7LessThan(Date value) {
            addCriterion("col_7 <", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7LessThanOrEqualTo(Date value) {
            addCriterion("col_7 <=", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7In(List<Date> values) {
            addCriterion("col_7 in", values, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotIn(List<Date> values) {
            addCriterion("col_7 not in", values, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7Between(Date value1, Date value2) {
            addCriterion("col_7 between", value1, value2, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotBetween(Date value1, Date value2) {
            addCriterion("col_7 not between", value1, value2, "col7");
            return (Criteria) this;
        }

        public Criteria andCol8IsNull() {
            addCriterion("col_8 is null");
            return (Criteria) this;
        }

        public Criteria andCol8IsNotNull() {
            addCriterion("col_8 is not null");
            return (Criteria) this;
        }

        public Criteria andCol8EqualTo(Date value) {
            addCriterion("col_8 =", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotEqualTo(Date value) {
            addCriterion("col_8 <>", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8GreaterThan(Date value) {
            addCriterion("col_8 >", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8GreaterThanOrEqualTo(Date value) {
            addCriterion("col_8 >=", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8LessThan(Date value) {
            addCriterion("col_8 <", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8LessThanOrEqualTo(Date value) {
            addCriterion("col_8 <=", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8In(List<Date> values) {
            addCriterion("col_8 in", values, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotIn(List<Date> values) {
            addCriterion("col_8 not in", values, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8Between(Date value1, Date value2) {
            addCriterion("col_8 between", value1, value2, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotBetween(Date value1, Date value2) {
            addCriterion("col_8 not between", value1, value2, "col8");
            return (Criteria) this;
        }

        public Criteria andCol9IsNull() {
            addCriterion("col_9 is null");
            return (Criteria) this;
        }

        public Criteria andCol9IsNotNull() {
            addCriterion("col_9 is not null");
            return (Criteria) this;
        }

        public Criteria andCol9EqualTo(Date value) {
            addCriterionForJDBCDate("col_9 =", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotEqualTo(Date value) {
            addCriterionForJDBCDate("col_9 <>", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9GreaterThan(Date value) {
            addCriterionForJDBCDate("col_9 >", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("col_9 >=", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9LessThan(Date value) {
            addCriterionForJDBCDate("col_9 <", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("col_9 <=", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9In(List<Date> values) {
            addCriterionForJDBCDate("col_9 in", values, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotIn(List<Date> values) {
            addCriterionForJDBCDate("col_9 not in", values, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9Between(Date value1, Date value2) {
            addCriterionForJDBCDate("col_9 between", value1, value2, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("col_9 not between", value1, value2, "col9");
            return (Criteria) this;
        }

        public Criteria andCol10IsNull() {
            addCriterion("col_10 is null");
            return (Criteria) this;
        }

        public Criteria andCol10IsNotNull() {
            addCriterion("col_10 is not null");
            return (Criteria) this;
        }

        public Criteria andCol10EqualTo(Boolean value) {
            addCriterion("col_10 =", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotEqualTo(Boolean value) {
            addCriterion("col_10 <>", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10GreaterThan(Boolean value) {
            addCriterion("col_10 >", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10GreaterThanOrEqualTo(Boolean value) {
            addCriterion("col_10 >=", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10LessThan(Boolean value) {
            addCriterion("col_10 <", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10LessThanOrEqualTo(Boolean value) {
            addCriterion("col_10 <=", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10In(List<Boolean> values) {
            addCriterion("col_10 in", values, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotIn(List<Boolean> values) {
            addCriterion("col_10 not in", values, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10Between(Boolean value1, Boolean value2) {
            addCriterion("col_10 between", value1, value2, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotBetween(Boolean value1, Boolean value2) {
            addCriterion("col_10 not between", value1, value2, "col10");
            return (Criteria) this;
        }

        public Criteria andCol13IsNull() {
            addCriterion("col_13 is null");
            return (Criteria) this;
        }

        public Criteria andCol13IsNotNull() {
            addCriterion("col_13 is not null");
            return (Criteria) this;
        }

        public Criteria andCol13EqualTo(Object value) {
            addCriterion("col_13 =", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotEqualTo(Object value) {
            addCriterion("col_13 <>", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13GreaterThan(Object value) {
            addCriterion("col_13 >", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13GreaterThanOrEqualTo(Object value) {
            addCriterion("col_13 >=", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13LessThan(Object value) {
            addCriterion("col_13 <", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13LessThanOrEqualTo(Object value) {
            addCriterion("col_13 <=", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13In(List<Object> values) {
            addCriterion("col_13 in", values, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotIn(List<Object> values) {
            addCriterion("col_13 not in", values, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13Between(Object value1, Object value2) {
            addCriterion("col_13 between", value1, value2, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotBetween(Object value1, Object value2) {
            addCriterion("col_13 not between", value1, value2, "col13");
            return (Criteria) this;
        }

        public Criteria andCol14IsNull() {
            addCriterion("col_14 is null");
            return (Criteria) this;
        }

        public Criteria andCol14IsNotNull() {
            addCriterion("col_14 is not null");
            return (Criteria) this;
        }

        public Criteria andCol14EqualTo(Object value) {
            addCriterion("col_14 =", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotEqualTo(Object value) {
            addCriterion("col_14 <>", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14GreaterThan(Object value) {
            addCriterion("col_14 >", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14GreaterThanOrEqualTo(Object value) {
            addCriterion("col_14 >=", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14LessThan(Object value) {
            addCriterion("col_14 <", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14LessThanOrEqualTo(Object value) {
            addCriterion("col_14 <=", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14In(List<Object> values) {
            addCriterion("col_14 in", values, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotIn(List<Object> values) {
            addCriterion("col_14 not in", values, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14Between(Object value1, Object value2) {
            addCriterion("col_14 between", value1, value2, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotBetween(Object value1, Object value2) {
            addCriterion("col_14 not between", value1, value2, "col14");
            return (Criteria) this;
        }

        public Criteria andCol15IsNull() {
            addCriterion("col_15 is null");
            return (Criteria) this;
        }

        public Criteria andCol15IsNotNull() {
            addCriterion("col_15 is not null");
            return (Criteria) this;
        }

        public Criteria andCol15EqualTo(Object value) {
            addCriterion("col_15 =", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15NotEqualTo(Object value) {
            addCriterion("col_15 <>", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15GreaterThan(Object value) {
            addCriterion("col_15 >", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15GreaterThanOrEqualTo(Object value) {
            addCriterion("col_15 >=", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15LessThan(Object value) {
            addCriterion("col_15 <", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15LessThanOrEqualTo(Object value) {
            addCriterion("col_15 <=", value, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15In(List<Object> values) {
            addCriterion("col_15 in", values, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15NotIn(List<Object> values) {
            addCriterion("col_15 not in", values, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15Between(Object value1, Object value2) {
            addCriterion("col_15 between", value1, value2, "col15");
            return (Criteria) this;
        }

        public Criteria andCol15NotBetween(Object value1, Object value2) {
            addCriterion("col_15 not between", value1, value2, "col15");
            return (Criteria) this;
        }

        public Criteria andCol16IsNull() {
            addCriterion("col_16 is null");
            return (Criteria) this;
        }

        public Criteria andCol16IsNotNull() {
            addCriterion("col_16 is not null");
            return (Criteria) this;
        }

        public Criteria andCol16EqualTo(Object value) {
            addCriterion("col_16 =", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotEqualTo(Object value) {
            addCriterion("col_16 <>", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16GreaterThan(Object value) {
            addCriterion("col_16 >", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16GreaterThanOrEqualTo(Object value) {
            addCriterion("col_16 >=", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16LessThan(Object value) {
            addCriterion("col_16 <", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16LessThanOrEqualTo(Object value) {
            addCriterion("col_16 <=", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16In(List<Object> values) {
            addCriterion("col_16 in", values, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotIn(List<Object> values) {
            addCriterion("col_16 not in", values, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16Between(Object value1, Object value2) {
            addCriterion("col_16 between", value1, value2, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotBetween(Object value1, Object value2) {
            addCriterion("col_16 not between", value1, value2, "col16");
            return (Criteria) this;
        }

        public Criteria andCol17IsNull() {
            addCriterion("col_17 is null");
            return (Criteria) this;
        }

        public Criteria andCol17IsNotNull() {
            addCriterion("col_17 is not null");
            return (Criteria) this;
        }

        public Criteria andCol17EqualTo(String value) {
            addCriterion("col_17 =", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotEqualTo(String value) {
            addCriterion("col_17 <>", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17GreaterThan(String value) {
            addCriterion("col_17 >", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17GreaterThanOrEqualTo(String value) {
            addCriterion("col_17 >=", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17LessThan(String value) {
            addCriterion("col_17 <", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17LessThanOrEqualTo(String value) {
            addCriterion("col_17 <=", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17Like(String value) {
            addCriterion("col_17 like", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotLike(String value) {
            addCriterion("col_17 not like", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17In(List<String> values) {
            addCriterion("col_17 in", values, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotIn(List<String> values) {
            addCriterion("col_17 not in", values, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17Between(String value1, String value2) {
            addCriterion("col_17 between", value1, value2, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotBetween(String value1, String value2) {
            addCriterion("col_17 not between", value1, value2, "col17");
            return (Criteria) this;
        }

        public Criteria andCol18IsNull() {
            addCriterion("col_18 is null");
            return (Criteria) this;
        }

        public Criteria andCol18IsNotNull() {
            addCriterion("col_18 is not null");
            return (Criteria) this;
        }

        public Criteria andCol18EqualTo(String value) {
            addCriterion("col_18 =", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotEqualTo(String value) {
            addCriterion("col_18 <>", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18GreaterThan(String value) {
            addCriterion("col_18 >", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18GreaterThanOrEqualTo(String value) {
            addCriterion("col_18 >=", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18LessThan(String value) {
            addCriterion("col_18 <", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18LessThanOrEqualTo(String value) {
            addCriterion("col_18 <=", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18Like(String value) {
            addCriterion("col_18 like", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotLike(String value) {
            addCriterion("col_18 not like", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18In(List<String> values) {
            addCriterion("col_18 in", values, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotIn(List<String> values) {
            addCriterion("col_18 not in", values, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18Between(String value1, String value2) {
            addCriterion("col_18 between", value1, value2, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotBetween(String value1, String value2) {
            addCriterion("col_18 not between", value1, value2, "col18");
            return (Criteria) this;
        }

        public Criteria andCol19IsNull() {
            addCriterion("col_19 is null");
            return (Criteria) this;
        }

        public Criteria andCol19IsNotNull() {
            addCriterion("col_19 is not null");
            return (Criteria) this;
        }

        public Criteria andCol19EqualTo(String value) {
            addCriterion("col_19 =", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotEqualTo(String value) {
            addCriterion("col_19 <>", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19GreaterThan(String value) {
            addCriterion("col_19 >", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19GreaterThanOrEqualTo(String value) {
            addCriterion("col_19 >=", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19LessThan(String value) {
            addCriterion("col_19 <", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19LessThanOrEqualTo(String value) {
            addCriterion("col_19 <=", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19Like(String value) {
            addCriterion("col_19 like", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotLike(String value) {
            addCriterion("col_19 not like", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19In(List<String> values) {
            addCriterion("col_19 in", values, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotIn(List<String> values) {
            addCriterion("col_19 not in", values, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19Between(String value1, String value2) {
            addCriterion("col_19 between", value1, value2, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotBetween(String value1, String value2) {
            addCriterion("col_19 not between", value1, value2, "col19");
            return (Criteria) this;
        }

        public Criteria andCol20IsNull() {
            addCriterion("col_20 is null");
            return (Criteria) this;
        }

        public Criteria andCol20IsNotNull() {
            addCriterion("col_20 is not null");
            return (Criteria) this;
        }

        public Criteria andCol20EqualTo(Long value) {
            addCriterion("col_20 =", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotEqualTo(Long value) {
            addCriterion("col_20 <>", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20GreaterThan(Long value) {
            addCriterion("col_20 >", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20GreaterThanOrEqualTo(Long value) {
            addCriterion("col_20 >=", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20LessThan(Long value) {
            addCriterion("col_20 <", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20LessThanOrEqualTo(Long value) {
            addCriterion("col_20 <=", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20In(List<Long> values) {
            addCriterion("col_20 in", values, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotIn(List<Long> values) {
            addCriterion("col_20 not in", values, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20Between(Long value1, Long value2) {
            addCriterion("col_20 between", value1, value2, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotBetween(Long value1, Long value2) {
            addCriterion("col_20 not between", value1, value2, "col20");
            return (Criteria) this;
        }

        public Criteria andCol21IsNull() {
            addCriterion("col_21 is null");
            return (Criteria) this;
        }

        public Criteria andCol21IsNotNull() {
            addCriterion("col_21 is not null");
            return (Criteria) this;
        }

        public Criteria andCol21EqualTo(BigDecimal value) {
            addCriterion("col_21 =", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotEqualTo(BigDecimal value) {
            addCriterion("col_21 <>", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21GreaterThan(BigDecimal value) {
            addCriterion("col_21 >", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("col_21 >=", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21LessThan(BigDecimal value) {
            addCriterion("col_21 <", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21LessThanOrEqualTo(BigDecimal value) {
            addCriterion("col_21 <=", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21In(List<BigDecimal> values) {
            addCriterion("col_21 in", values, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotIn(List<BigDecimal> values) {
            addCriterion("col_21 not in", values, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("col_21 between", value1, value2, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("col_21 not between", value1, value2, "col21");
            return (Criteria) this;
        }

        public Criteria andCol22IsNull() {
            addCriterion("col_22 is null");
            return (Criteria) this;
        }

        public Criteria andCol22IsNotNull() {
            addCriterion("col_22 is not null");
            return (Criteria) this;
        }

        public Criteria andCol22EqualTo(Date value) {
            addCriterion("col_22 =", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotEqualTo(Date value) {
            addCriterion("col_22 <>", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22GreaterThan(Date value) {
            addCriterion("col_22 >", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22GreaterThanOrEqualTo(Date value) {
            addCriterion("col_22 >=", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22LessThan(Date value) {
            addCriterion("col_22 <", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22LessThanOrEqualTo(Date value) {
            addCriterion("col_22 <=", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22In(List<Date> values) {
            addCriterion("col_22 in", values, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotIn(List<Date> values) {
            addCriterion("col_22 not in", values, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22Between(Date value1, Date value2) {
            addCriterion("col_22 between", value1, value2, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotBetween(Date value1, Date value2) {
            addCriterion("col_22 not between", value1, value2, "col22");
            return (Criteria) this;
        }

        public Criteria andCol23IsNull() {
            addCriterion("col_23 is null");
            return (Criteria) this;
        }

        public Criteria andCol23IsNotNull() {
            addCriterion("col_23 is not null");
            return (Criteria) this;
        }

        public Criteria andCol23EqualTo(Date value) {
            addCriterion("col_23 =", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotEqualTo(Date value) {
            addCriterion("col_23 <>", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23GreaterThan(Date value) {
            addCriterion("col_23 >", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23GreaterThanOrEqualTo(Date value) {
            addCriterion("col_23 >=", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23LessThan(Date value) {
            addCriterion("col_23 <", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23LessThanOrEqualTo(Date value) {
            addCriterion("col_23 <=", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23In(List<Date> values) {
            addCriterion("col_23 in", values, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotIn(List<Date> values) {
            addCriterion("col_23 not in", values, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23Between(Date value1, Date value2) {
            addCriterion("col_23 between", value1, value2, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotBetween(Date value1, Date value2) {
            addCriterion("col_23 not between", value1, value2, "col23");
            return (Criteria) this;
        }

        public Criteria andCol24IsNull() {
            addCriterion("col_24 is null");
            return (Criteria) this;
        }

        public Criteria andCol24IsNotNull() {
            addCriterion("col_24 is not null");
            return (Criteria) this;
        }

        public Criteria andCol24EqualTo(Date value) {
            addCriterion("col_24 =", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotEqualTo(Date value) {
            addCriterion("col_24 <>", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24GreaterThan(Date value) {
            addCriterion("col_24 >", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24GreaterThanOrEqualTo(Date value) {
            addCriterion("col_24 >=", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24LessThan(Date value) {
            addCriterion("col_24 <", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24LessThanOrEqualTo(Date value) {
            addCriterion("col_24 <=", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24In(List<Date> values) {
            addCriterion("col_24 in", values, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotIn(List<Date> values) {
            addCriterion("col_24 not in", values, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24Between(Date value1, Date value2) {
            addCriterion("col_24 between", value1, value2, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotBetween(Date value1, Date value2) {
            addCriterion("col_24 not between", value1, value2, "col24");
            return (Criteria) this;
        }

        public Criteria andCol25IsNull() {
            addCriterion("col_25 is null");
            return (Criteria) this;
        }

        public Criteria andCol25IsNotNull() {
            addCriterion("col_25 is not null");
            return (Criteria) this;
        }

        public Criteria andCol25EqualTo(Date value) {
            addCriterionForJDBCDate("col_25 =", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotEqualTo(Date value) {
            addCriterionForJDBCDate("col_25 <>", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25GreaterThan(Date value) {
            addCriterionForJDBCDate("col_25 >", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("col_25 >=", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25LessThan(Date value) {
            addCriterionForJDBCDate("col_25 <", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("col_25 <=", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25In(List<Date> values) {
            addCriterionForJDBCDate("col_25 in", values, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotIn(List<Date> values) {
            addCriterionForJDBCDate("col_25 not in", values, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25Between(Date value1, Date value2) {
            addCriterionForJDBCDate("col_25 between", value1, value2, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("col_25 not between", value1, value2, "col25");
            return (Criteria) this;
        }

        public Criteria andCol26IsNull() {
            addCriterion("col_26 is null");
            return (Criteria) this;
        }

        public Criteria andCol26IsNotNull() {
            addCriterion("col_26 is not null");
            return (Criteria) this;
        }

        public Criteria andCol26EqualTo(Boolean value) {
            addCriterion("col_26 =", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotEqualTo(Boolean value) {
            addCriterion("col_26 <>", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26GreaterThan(Boolean value) {
            addCriterion("col_26 >", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26GreaterThanOrEqualTo(Boolean value) {
            addCriterion("col_26 >=", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26LessThan(Boolean value) {
            addCriterion("col_26 <", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26LessThanOrEqualTo(Boolean value) {
            addCriterion("col_26 <=", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26In(List<Boolean> values) {
            addCriterion("col_26 in", values, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotIn(List<Boolean> values) {
            addCriterion("col_26 not in", values, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26Between(Boolean value1, Boolean value2) {
            addCriterion("col_26 between", value1, value2, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotBetween(Boolean value1, Boolean value2) {
            addCriterion("col_26 not between", value1, value2, "col26");
            return (Criteria) this;
        }

        public Criteria andCol29IsNull() {
            addCriterion("col_29 is null");
            return (Criteria) this;
        }

        public Criteria andCol29IsNotNull() {
            addCriterion("col_29 is not null");
            return (Criteria) this;
        }

        public Criteria andCol29EqualTo(Object value) {
            addCriterion("col_29 =", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotEqualTo(Object value) {
            addCriterion("col_29 <>", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29GreaterThan(Object value) {
            addCriterion("col_29 >", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29GreaterThanOrEqualTo(Object value) {
            addCriterion("col_29 >=", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29LessThan(Object value) {
            addCriterion("col_29 <", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29LessThanOrEqualTo(Object value) {
            addCriterion("col_29 <=", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29In(List<Object> values) {
            addCriterion("col_29 in", values, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotIn(List<Object> values) {
            addCriterion("col_29 not in", values, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29Between(Object value1, Object value2) {
            addCriterion("col_29 between", value1, value2, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotBetween(Object value1, Object value2) {
            addCriterion("col_29 not between", value1, value2, "col29");
            return (Criteria) this;
        }

        public Criteria andCol30IsNull() {
            addCriterion("col_30 is null");
            return (Criteria) this;
        }

        public Criteria andCol30IsNotNull() {
            addCriterion("col_30 is not null");
            return (Criteria) this;
        }

        public Criteria andCol30EqualTo(Object value) {
            addCriterion("col_30 =", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotEqualTo(Object value) {
            addCriterion("col_30 <>", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30GreaterThan(Object value) {
            addCriterion("col_30 >", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30GreaterThanOrEqualTo(Object value) {
            addCriterion("col_30 >=", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30LessThan(Object value) {
            addCriterion("col_30 <", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30LessThanOrEqualTo(Object value) {
            addCriterion("col_30 <=", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30In(List<Object> values) {
            addCriterion("col_30 in", values, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotIn(List<Object> values) {
            addCriterion("col_30 not in", values, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30Between(Object value1, Object value2) {
            addCriterion("col_30 between", value1, value2, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotBetween(Object value1, Object value2) {
            addCriterion("col_30 not between", value1, value2, "col30");
            return (Criteria) this;
        }

        public Criteria andCol31IsNull() {
            addCriterion("col_31 is null");
            return (Criteria) this;
        }

        public Criteria andCol31IsNotNull() {
            addCriterion("col_31 is not null");
            return (Criteria) this;
        }

        public Criteria andCol31EqualTo(Object value) {
            addCriterion("col_31 =", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31NotEqualTo(Object value) {
            addCriterion("col_31 <>", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31GreaterThan(Object value) {
            addCriterion("col_31 >", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31GreaterThanOrEqualTo(Object value) {
            addCriterion("col_31 >=", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31LessThan(Object value) {
            addCriterion("col_31 <", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31LessThanOrEqualTo(Object value) {
            addCriterion("col_31 <=", value, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31In(List<Object> values) {
            addCriterion("col_31 in", values, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31NotIn(List<Object> values) {
            addCriterion("col_31 not in", values, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31Between(Object value1, Object value2) {
            addCriterion("col_31 between", value1, value2, "col31");
            return (Criteria) this;
        }

        public Criteria andCol31NotBetween(Object value1, Object value2) {
            addCriterion("col_31 not between", value1, value2, "col31");
            return (Criteria) this;
        }

        public Criteria andCol32IsNull() {
            addCriterion("col_32 is null");
            return (Criteria) this;
        }

        public Criteria andCol32IsNotNull() {
            addCriterion("col_32 is not null");
            return (Criteria) this;
        }

        public Criteria andCol32EqualTo(Object value) {
            addCriterion("col_32 =", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32NotEqualTo(Object value) {
            addCriterion("col_32 <>", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32GreaterThan(Object value) {
            addCriterion("col_32 >", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32GreaterThanOrEqualTo(Object value) {
            addCriterion("col_32 >=", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32LessThan(Object value) {
            addCriterion("col_32 <", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32LessThanOrEqualTo(Object value) {
            addCriterion("col_32 <=", value, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32In(List<Object> values) {
            addCriterion("col_32 in", values, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32NotIn(List<Object> values) {
            addCriterion("col_32 not in", values, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32Between(Object value1, Object value2) {
            addCriterion("col_32 between", value1, value2, "col32");
            return (Criteria) this;
        }

        public Criteria andCol32NotBetween(Object value1, Object value2) {
            addCriterion("col_32 not between", value1, value2, "col32");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.test_tbl
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 27 22:16:26 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.test_tbl
     *
     * @mbg.generated Sun Sep 27 22:16:26 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}