-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
--   TBL削除(存在する場合) [顧客 / CUSTOMERS]
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
DROP TABLE IF EXISTS SYSTEM.CUSTOMERS;

-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
--   TBL作成 [顧客 / CUSTOMERS]
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
--[項目名(論理)] 1:顧客ID      / 2:顧客名        / 3:メールアドレス / 4:電話番号 / 5:住所    / 6:登録日時   / 7:更新日時  
--[項目名(物理)] 1:CUSTOMER_ID / 2:CUSTOMER_NAME / 3:EMAIL          / 4:PHONE    / 5:ADDRESS / 6:CREATED_AT / 7:UPDATED_AT
CREATE TABLE SYSTEM.CUSTOMERS(
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(255) DEFAULT NULL,
    PHONE VARCHAR2(20) DEFAULT NULL,
    ADDRESS NVARCHAR2(255) DEFAULT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PRIMARY KEY(CUSTOMER_ID)
);

-- ==================================================
--  論理名 追加 [顧客 / CUSTOMERS]
-- ==================================================
COMMENT ON TABLE SYSTEM.CUSTOMERS IS '顧客';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.CUSTOMER_ID IS '顧客ID';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.CUSTOMER_NAME IS '顧客名';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.EMAIL IS 'メールアドレス';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.PHONE IS '電話番号';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.ADDRESS IS '住所';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.CREATED_AT IS '登録日時';
COMMENT ON COLUMN SYSTEM.CUSTOMERS.UPDATED_AT IS '更新日時';
