package com.example.mapper;

import com.example.entity.Orders;
import com.example.entity.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insert(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insertSelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    Orders selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExampleSelective(@Param("row") Orders row, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExample(@Param("row") Orders row, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKeySelective(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKey(Orders row);
}