package com.example.mapper;

import com.example.entity.OrderDetails;
import com.example.entity.OrderDetailsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    long countByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByPrimaryKey(Long orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insert(OrderDetails row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insertSelective(OrderDetails row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    List<OrderDetails> selectByExample(OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    OrderDetails selectByPrimaryKey(Long orderDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExampleSelective(@Param("row") OrderDetails row, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExample(@Param("row") OrderDetails row, @Param("example") OrderDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKeySelective(OrderDetails row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_details
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKey(OrderDetails row);
}