package com.example.mapper;

import com.example.entity.Products;
import com.example.entity.ProductsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    long countByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int deleteByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insert(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int insertSelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    List<Products> selectByExample(ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    Products selectByPrimaryKey(Long productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExampleSelective(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByExample(@Param("row") Products row, @Param("example") ProductsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKeySelective(Products row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    int updateByPrimaryKey(Products row);
}