package com.example.entity.system;

import java.math.BigDecimal;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDER_DETAILS.ORDER_DETAIL_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDER_DETAILS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDER_DETAILS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDER_DETAILS.QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.ORDER_DETAILS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private BigDecimal unitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDER_DETAILS.ORDER_DETAIL_ID
     *
     * @return the value of SYSTEM.ORDER_DETAILS.ORDER_DETAIL_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDER_DETAILS.ORDER_DETAIL_ID
     *
     * @param orderDetailId the value for SYSTEM.ORDER_DETAILS.ORDER_DETAIL_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDER_DETAILS.ORDER_ID
     *
     * @return the value of SYSTEM.ORDER_DETAILS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDER_DETAILS.ORDER_ID
     *
     * @param orderId the value for SYSTEM.ORDER_DETAILS.ORDER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDER_DETAILS.PRODUCT_ID
     *
     * @return the value of SYSTEM.ORDER_DETAILS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDER_DETAILS.PRODUCT_ID
     *
     * @param productId the value for SYSTEM.ORDER_DETAILS.PRODUCT_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDER_DETAILS.QUANTITY
     *
     * @return the value of SYSTEM.ORDER_DETAILS.QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDER_DETAILS.QUANTITY
     *
     * @param quantity the value for SYSTEM.ORDER_DETAILS.QUANTITY
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.ORDER_DETAILS.UNIT_PRICE
     *
     * @return the value of SYSTEM.ORDER_DETAILS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.ORDER_DETAILS.UNIT_PRICE
     *
     * @param unitPrice the value for SYSTEM.ORDER_DETAILS.UNIT_PRICE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}