package com.example.mapper.system;

import com.example.entity.system.Customers;
import com.example.entity.system.CustomersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    long countByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int deleteByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int deleteByPrimaryKey(Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int insert(Customers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int insertSelective(Customers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    List<Customers> selectByExample(CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    Customers selectByPrimaryKey(Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int updateByExampleSelective(@Param("row") Customers row, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int updateByExample(@Param("row") Customers row, @Param("example") CustomersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int updateByPrimaryKeySelective(Customers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYSTEM.CUSTOMERS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    int updateByPrimaryKey(Customers row);
}