package com.example.entity.system;

import java.util.Date;

public class Customers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.EMAIL
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.PHONE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.ADDRESS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYSTEM.CUSTOMERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.CUSTOMER_ID
     *
     * @return the value of SYSTEM.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.CUSTOMER_ID
     *
     * @param customerId the value for SYSTEM.CUSTOMERS.CUSTOMER_ID
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.CUSTOMER_NAME
     *
     * @return the value of SYSTEM.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.CUSTOMER_NAME
     *
     * @param customerName the value for SYSTEM.CUSTOMERS.CUSTOMER_NAME
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.EMAIL
     *
     * @return the value of SYSTEM.CUSTOMERS.EMAIL
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.EMAIL
     *
     * @param email the value for SYSTEM.CUSTOMERS.EMAIL
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.PHONE
     *
     * @return the value of SYSTEM.CUSTOMERS.PHONE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.PHONE
     *
     * @param phone the value for SYSTEM.CUSTOMERS.PHONE
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.ADDRESS
     *
     * @return the value of SYSTEM.CUSTOMERS.ADDRESS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.ADDRESS
     *
     * @param address the value for SYSTEM.CUSTOMERS.ADDRESS
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.CREATED_AT
     *
     * @return the value of SYSTEM.CUSTOMERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.CREATED_AT
     *
     * @param createdAt the value for SYSTEM.CUSTOMERS.CREATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYSTEM.CUSTOMERS.UPDATED_AT
     *
     * @return the value of SYSTEM.CUSTOMERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYSTEM.CUSTOMERS.UPDATED_AT
     *
     * @param updatedAt the value for SYSTEM.CUSTOMERS.UPDATED_AT
     *
     * @mbg.generated Thu Sep 24 21:52:27 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}