package com.example.entity;

import java.util.Date;

public class Customers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customer_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.customer_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.email
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.phone
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.address
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customer_id
     *
     * @return the value of customers.customer_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customer_id
     *
     * @param customerId the value for customers.customer_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.customer_name
     *
     * @return the value of customers.customer_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.customer_name
     *
     * @param customerName the value for customers.customer_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.email
     *
     * @return the value of customers.email
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.email
     *
     * @param email the value for customers.email
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.phone
     *
     * @return the value of customers.phone
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.phone
     *
     * @param phone the value for customers.phone
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.address
     *
     * @return the value of customers.address
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.address
     *
     * @param address the value for customers.address
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.created_at
     *
     * @return the value of customers.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.created_at
     *
     * @param createdAt the value for customers.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.updated_at
     *
     * @return the value of customers.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.updated_at
     *
     * @param updatedAt the value for customers.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}