package com.example.entity;

import java.math.BigDecimal;

public class OrderDetails {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.order_detail_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.order_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_details.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private BigDecimal unitPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.order_detail_id
     *
     * @return the value of order_details.order_detail_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.order_detail_id
     *
     * @param orderDetailId the value for order_details.order_detail_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.order_id
     *
     * @return the value of order_details.order_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.order_id
     *
     * @param orderId the value for order_details.order_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.product_id
     *
     * @return the value of order_details.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.product_id
     *
     * @param productId the value for order_details.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.quantity
     *
     * @return the value of order_details.quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.quantity
     *
     * @param quantity the value for order_details.quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setQuantity(Long quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_details.unit_price
     *
     * @return the value of order_details.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_details.unit_price
     *
     * @param unitPrice the value for order_details.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
}