package com.example.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.product_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private BigDecimal unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.stock_quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Integer stockQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column products.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_id
     *
     * @return the value of products.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_id
     *
     * @param productId the value for products.product_id
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.product_name
     *
     * @return the value of products.product_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.product_name
     *
     * @param productName the value for products.product_name
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.unit_price
     *
     * @return the value of products.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.unit_price
     *
     * @param unitPrice the value for products.unit_price
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.stock_quantity
     *
     * @return the value of products.stock_quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Integer getStockQuantity() {
        return stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.stock_quantity
     *
     * @param stockQuantity the value for products.stock_quantity
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.created_at
     *
     * @return the value of products.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.created_at
     *
     * @param createdAt the value for products.created_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column products.updated_at
     *
     * @return the value of products.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column products.updated_at
     *
     * @param updatedAt the value for products.updated_at
     *
     * @mbg.generated Thu Sep 24 20:13:09 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}