package com.example.entity.dbo;

public class TestTblWithBLOBs extends TestTbl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_11
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private byte[] col11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_12
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private byte[] col12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_15
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private String col15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_27
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private byte[] col27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_28
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private byte[] col28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.TEST_TBL.COL_31
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    private String col31;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_11
     *
     * @return the value of dbo.TEST_TBL.COL_11
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public byte[] getCol11() {
        return col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_11
     *
     * @param col11 the value for dbo.TEST_TBL.COL_11
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol11(byte[] col11) {
        this.col11 = col11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_12
     *
     * @return the value of dbo.TEST_TBL.COL_12
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public byte[] getCol12() {
        return col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_12
     *
     * @param col12 the value for dbo.TEST_TBL.COL_12
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol12(byte[] col12) {
        this.col12 = col12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_15
     *
     * @return the value of dbo.TEST_TBL.COL_15
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public String getCol15() {
        return col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_15
     *
     * @param col15 the value for dbo.TEST_TBL.COL_15
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol15(String col15) {
        this.col15 = col15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_27
     *
     * @return the value of dbo.TEST_TBL.COL_27
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public byte[] getCol27() {
        return col27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_27
     *
     * @param col27 the value for dbo.TEST_TBL.COL_27
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol27(byte[] col27) {
        this.col27 = col27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_28
     *
     * @return the value of dbo.TEST_TBL.COL_28
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public byte[] getCol28() {
        return col28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_28
     *
     * @param col28 the value for dbo.TEST_TBL.COL_28
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol28(byte[] col28) {
        this.col28 = col28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.TEST_TBL.COL_31
     *
     * @return the value of dbo.TEST_TBL.COL_31
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public String getCol31() {
        return col31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.TEST_TBL.COL_31
     *
     * @param col31 the value for dbo.TEST_TBL.COL_31
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setCol31(String col31) {
        this.col31 = col31;
    }
}