package com.example.entity.dbo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TestTblExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public TestTblExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCol1IsNull() {
            addCriterion("COL_1 is null");
            return (Criteria) this;
        }

        public Criteria andCol1IsNotNull() {
            addCriterion("COL_1 is not null");
            return (Criteria) this;
        }

        public Criteria andCol1EqualTo(String value) {
            addCriterion("COL_1 =", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotEqualTo(String value) {
            addCriterion("COL_1 <>", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1GreaterThan(String value) {
            addCriterion("COL_1 >", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1GreaterThanOrEqualTo(String value) {
            addCriterion("COL_1 >=", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1LessThan(String value) {
            addCriterion("COL_1 <", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1LessThanOrEqualTo(String value) {
            addCriterion("COL_1 <=", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1Like(String value) {
            addCriterion("COL_1 like", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotLike(String value) {
            addCriterion("COL_1 not like", value, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1In(List<String> values) {
            addCriterion("COL_1 in", values, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotIn(List<String> values) {
            addCriterion("COL_1 not in", values, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1Between(String value1, String value2) {
            addCriterion("COL_1 between", value1, value2, "col1");
            return (Criteria) this;
        }

        public Criteria andCol1NotBetween(String value1, String value2) {
            addCriterion("COL_1 not between", value1, value2, "col1");
            return (Criteria) this;
        }

        public Criteria andCol2IsNull() {
            addCriterion("COL_2 is null");
            return (Criteria) this;
        }

        public Criteria andCol2IsNotNull() {
            addCriterion("COL_2 is not null");
            return (Criteria) this;
        }

        public Criteria andCol2EqualTo(String value) {
            addCriterion("COL_2 =", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotEqualTo(String value) {
            addCriterion("COL_2 <>", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2GreaterThan(String value) {
            addCriterion("COL_2 >", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2GreaterThanOrEqualTo(String value) {
            addCriterion("COL_2 >=", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2LessThan(String value) {
            addCriterion("COL_2 <", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2LessThanOrEqualTo(String value) {
            addCriterion("COL_2 <=", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2Like(String value) {
            addCriterion("COL_2 like", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotLike(String value) {
            addCriterion("COL_2 not like", value, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2In(List<String> values) {
            addCriterion("COL_2 in", values, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotIn(List<String> values) {
            addCriterion("COL_2 not in", values, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2Between(String value1, String value2) {
            addCriterion("COL_2 between", value1, value2, "col2");
            return (Criteria) this;
        }

        public Criteria andCol2NotBetween(String value1, String value2) {
            addCriterion("COL_2 not between", value1, value2, "col2");
            return (Criteria) this;
        }

        public Criteria andCol3IsNull() {
            addCriterion("COL_3 is null");
            return (Criteria) this;
        }

        public Criteria andCol3IsNotNull() {
            addCriterion("COL_3 is not null");
            return (Criteria) this;
        }

        public Criteria andCol3EqualTo(String value) {
            addCriterion("COL_3 =", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotEqualTo(String value) {
            addCriterion("COL_3 <>", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3GreaterThan(String value) {
            addCriterion("COL_3 >", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3GreaterThanOrEqualTo(String value) {
            addCriterion("COL_3 >=", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3LessThan(String value) {
            addCriterion("COL_3 <", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3LessThanOrEqualTo(String value) {
            addCriterion("COL_3 <=", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3Like(String value) {
            addCriterion("COL_3 like", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotLike(String value) {
            addCriterion("COL_3 not like", value, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3In(List<String> values) {
            addCriterion("COL_3 in", values, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotIn(List<String> values) {
            addCriterion("COL_3 not in", values, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3Between(String value1, String value2) {
            addCriterion("COL_3 between", value1, value2, "col3");
            return (Criteria) this;
        }

        public Criteria andCol3NotBetween(String value1, String value2) {
            addCriterion("COL_3 not between", value1, value2, "col3");
            return (Criteria) this;
        }

        public Criteria andCol4IsNull() {
            addCriterion("COL_4 is null");
            return (Criteria) this;
        }

        public Criteria andCol4IsNotNull() {
            addCriterion("COL_4 is not null");
            return (Criteria) this;
        }

        public Criteria andCol4EqualTo(Long value) {
            addCriterion("COL_4 =", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotEqualTo(Long value) {
            addCriterion("COL_4 <>", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4GreaterThan(Long value) {
            addCriterion("COL_4 >", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4GreaterThanOrEqualTo(Long value) {
            addCriterion("COL_4 >=", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4LessThan(Long value) {
            addCriterion("COL_4 <", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4LessThanOrEqualTo(Long value) {
            addCriterion("COL_4 <=", value, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4In(List<Long> values) {
            addCriterion("COL_4 in", values, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotIn(List<Long> values) {
            addCriterion("COL_4 not in", values, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4Between(Long value1, Long value2) {
            addCriterion("COL_4 between", value1, value2, "col4");
            return (Criteria) this;
        }

        public Criteria andCol4NotBetween(Long value1, Long value2) {
            addCriterion("COL_4 not between", value1, value2, "col4");
            return (Criteria) this;
        }

        public Criteria andCol5IsNull() {
            addCriterion("COL_5 is null");
            return (Criteria) this;
        }

        public Criteria andCol5IsNotNull() {
            addCriterion("COL_5 is not null");
            return (Criteria) this;
        }

        public Criteria andCol5EqualTo(BigDecimal value) {
            addCriterion("COL_5 =", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotEqualTo(BigDecimal value) {
            addCriterion("COL_5 <>", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5GreaterThan(BigDecimal value) {
            addCriterion("COL_5 >", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COL_5 >=", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5LessThan(BigDecimal value) {
            addCriterion("COL_5 <", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5LessThanOrEqualTo(BigDecimal value) {
            addCriterion("COL_5 <=", value, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5In(List<BigDecimal> values) {
            addCriterion("COL_5 in", values, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotIn(List<BigDecimal> values) {
            addCriterion("COL_5 not in", values, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("COL_5 between", value1, value2, "col5");
            return (Criteria) this;
        }

        public Criteria andCol5NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COL_5 not between", value1, value2, "col5");
            return (Criteria) this;
        }

        public Criteria andCol6IsNull() {
            addCriterion("COL_6 is null");
            return (Criteria) this;
        }

        public Criteria andCol6IsNotNull() {
            addCriterion("COL_6 is not null");
            return (Criteria) this;
        }

        public Criteria andCol6EqualTo(Object value) {
            addCriterion("COL_6 =", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotEqualTo(Object value) {
            addCriterion("COL_6 <>", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6GreaterThan(Object value) {
            addCriterion("COL_6 >", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6GreaterThanOrEqualTo(Object value) {
            addCriterion("COL_6 >=", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6LessThan(Object value) {
            addCriterion("COL_6 <", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6LessThanOrEqualTo(Object value) {
            addCriterion("COL_6 <=", value, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6In(List<Object> values) {
            addCriterion("COL_6 in", values, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotIn(List<Object> values) {
            addCriterion("COL_6 not in", values, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6Between(Object value1, Object value2) {
            addCriterion("COL_6 between", value1, value2, "col6");
            return (Criteria) this;
        }

        public Criteria andCol6NotBetween(Object value1, Object value2) {
            addCriterion("COL_6 not between", value1, value2, "col6");
            return (Criteria) this;
        }

        public Criteria andCol7IsNull() {
            addCriterion("COL_7 is null");
            return (Criteria) this;
        }

        public Criteria andCol7IsNotNull() {
            addCriterion("COL_7 is not null");
            return (Criteria) this;
        }

        public Criteria andCol7EqualTo(Object value) {
            addCriterion("COL_7 =", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotEqualTo(Object value) {
            addCriterion("COL_7 <>", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7GreaterThan(Object value) {
            addCriterion("COL_7 >", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7GreaterThanOrEqualTo(Object value) {
            addCriterion("COL_7 >=", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7LessThan(Object value) {
            addCriterion("COL_7 <", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7LessThanOrEqualTo(Object value) {
            addCriterion("COL_7 <=", value, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7In(List<Object> values) {
            addCriterion("COL_7 in", values, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotIn(List<Object> values) {
            addCriterion("COL_7 not in", values, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7Between(Object value1, Object value2) {
            addCriterion("COL_7 between", value1, value2, "col7");
            return (Criteria) this;
        }

        public Criteria andCol7NotBetween(Object value1, Object value2) {
            addCriterion("COL_7 not between", value1, value2, "col7");
            return (Criteria) this;
        }

        public Criteria andCol8IsNull() {
            addCriterion("COL_8 is null");
            return (Criteria) this;
        }

        public Criteria andCol8IsNotNull() {
            addCriterion("COL_8 is not null");
            return (Criteria) this;
        }

        public Criteria andCol8EqualTo(Date value) {
            addCriterion("COL_8 =", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotEqualTo(Date value) {
            addCriterion("COL_8 <>", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8GreaterThan(Date value) {
            addCriterion("COL_8 >", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8GreaterThanOrEqualTo(Date value) {
            addCriterion("COL_8 >=", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8LessThan(Date value) {
            addCriterion("COL_8 <", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8LessThanOrEqualTo(Date value) {
            addCriterion("COL_8 <=", value, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8In(List<Date> values) {
            addCriterion("COL_8 in", values, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotIn(List<Date> values) {
            addCriterion("COL_8 not in", values, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8Between(Date value1, Date value2) {
            addCriterion("COL_8 between", value1, value2, "col8");
            return (Criteria) this;
        }

        public Criteria andCol8NotBetween(Date value1, Date value2) {
            addCriterion("COL_8 not between", value1, value2, "col8");
            return (Criteria) this;
        }

        public Criteria andCol9IsNull() {
            addCriterion("COL_9 is null");
            return (Criteria) this;
        }

        public Criteria andCol9IsNotNull() {
            addCriterion("COL_9 is not null");
            return (Criteria) this;
        }

        public Criteria andCol9EqualTo(Date value) {
            addCriterionForJDBCDate("COL_9 =", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotEqualTo(Date value) {
            addCriterionForJDBCDate("COL_9 <>", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9GreaterThan(Date value) {
            addCriterionForJDBCDate("COL_9 >", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COL_9 >=", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9LessThan(Date value) {
            addCriterionForJDBCDate("COL_9 <", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COL_9 <=", value, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9In(List<Date> values) {
            addCriterionForJDBCDate("COL_9 in", values, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotIn(List<Date> values) {
            addCriterionForJDBCDate("COL_9 not in", values, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9Between(Date value1, Date value2) {
            addCriterionForJDBCDate("COL_9 between", value1, value2, "col9");
            return (Criteria) this;
        }

        public Criteria andCol9NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("COL_9 not between", value1, value2, "col9");
            return (Criteria) this;
        }

        public Criteria andCol10IsNull() {
            addCriterion("COL_10 is null");
            return (Criteria) this;
        }

        public Criteria andCol10IsNotNull() {
            addCriterion("COL_10 is not null");
            return (Criteria) this;
        }

        public Criteria andCol10EqualTo(Boolean value) {
            addCriterion("COL_10 =", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotEqualTo(Boolean value) {
            addCriterion("COL_10 <>", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10GreaterThan(Boolean value) {
            addCriterion("COL_10 >", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10GreaterThanOrEqualTo(Boolean value) {
            addCriterion("COL_10 >=", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10LessThan(Boolean value) {
            addCriterion("COL_10 <", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10LessThanOrEqualTo(Boolean value) {
            addCriterion("COL_10 <=", value, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10In(List<Boolean> values) {
            addCriterion("COL_10 in", values, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotIn(List<Boolean> values) {
            addCriterion("COL_10 not in", values, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10Between(Boolean value1, Boolean value2) {
            addCriterion("COL_10 between", value1, value2, "col10");
            return (Criteria) this;
        }

        public Criteria andCol10NotBetween(Boolean value1, Boolean value2) {
            addCriterion("COL_10 not between", value1, value2, "col10");
            return (Criteria) this;
        }

        public Criteria andCol13IsNull() {
            addCriterion("COL_13 is null");
            return (Criteria) this;
        }

        public Criteria andCol13IsNotNull() {
            addCriterion("COL_13 is not null");
            return (Criteria) this;
        }

        public Criteria andCol13EqualTo(String value) {
            addCriterion("COL_13 =", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotEqualTo(String value) {
            addCriterion("COL_13 <>", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13GreaterThan(String value) {
            addCriterion("COL_13 >", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13GreaterThanOrEqualTo(String value) {
            addCriterion("COL_13 >=", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13LessThan(String value) {
            addCriterion("COL_13 <", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13LessThanOrEqualTo(String value) {
            addCriterion("COL_13 <=", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13Like(String value) {
            addCriterion("COL_13 like", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotLike(String value) {
            addCriterion("COL_13 not like", value, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13In(List<String> values) {
            addCriterion("COL_13 in", values, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotIn(List<String> values) {
            addCriterion("COL_13 not in", values, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13Between(String value1, String value2) {
            addCriterion("COL_13 between", value1, value2, "col13");
            return (Criteria) this;
        }

        public Criteria andCol13NotBetween(String value1, String value2) {
            addCriterion("COL_13 not between", value1, value2, "col13");
            return (Criteria) this;
        }

        public Criteria andCol14IsNull() {
            addCriterion("COL_14 is null");
            return (Criteria) this;
        }

        public Criteria andCol14IsNotNull() {
            addCriterion("COL_14 is not null");
            return (Criteria) this;
        }

        public Criteria andCol14EqualTo(String value) {
            addCriterion("COL_14 =", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotEqualTo(String value) {
            addCriterion("COL_14 <>", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14GreaterThan(String value) {
            addCriterion("COL_14 >", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14GreaterThanOrEqualTo(String value) {
            addCriterion("COL_14 >=", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14LessThan(String value) {
            addCriterion("COL_14 <", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14LessThanOrEqualTo(String value) {
            addCriterion("COL_14 <=", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14Like(String value) {
            addCriterion("COL_14 like", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotLike(String value) {
            addCriterion("COL_14 not like", value, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14In(List<String> values) {
            addCriterion("COL_14 in", values, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotIn(List<String> values) {
            addCriterion("COL_14 not in", values, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14Between(String value1, String value2) {
            addCriterion("COL_14 between", value1, value2, "col14");
            return (Criteria) this;
        }

        public Criteria andCol14NotBetween(String value1, String value2) {
            addCriterion("COL_14 not between", value1, value2, "col14");
            return (Criteria) this;
        }

        public Criteria andCol16IsNull() {
            addCriterion("COL_16 is null");
            return (Criteria) this;
        }

        public Criteria andCol16IsNotNull() {
            addCriterion("COL_16 is not null");
            return (Criteria) this;
        }

        public Criteria andCol16EqualTo(String value) {
            addCriterion("COL_16 =", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotEqualTo(String value) {
            addCriterion("COL_16 <>", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16GreaterThan(String value) {
            addCriterion("COL_16 >", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16GreaterThanOrEqualTo(String value) {
            addCriterion("COL_16 >=", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16LessThan(String value) {
            addCriterion("COL_16 <", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16LessThanOrEqualTo(String value) {
            addCriterion("COL_16 <=", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16Like(String value) {
            addCriterion("COL_16 like", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotLike(String value) {
            addCriterion("COL_16 not like", value, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16In(List<String> values) {
            addCriterion("COL_16 in", values, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotIn(List<String> values) {
            addCriterion("COL_16 not in", values, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16Between(String value1, String value2) {
            addCriterion("COL_16 between", value1, value2, "col16");
            return (Criteria) this;
        }

        public Criteria andCol16NotBetween(String value1, String value2) {
            addCriterion("COL_16 not between", value1, value2, "col16");
            return (Criteria) this;
        }

        public Criteria andCol17IsNull() {
            addCriterion("COL_17 is null");
            return (Criteria) this;
        }

        public Criteria andCol17IsNotNull() {
            addCriterion("COL_17 is not null");
            return (Criteria) this;
        }

        public Criteria andCol17EqualTo(String value) {
            addCriterion("COL_17 =", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotEqualTo(String value) {
            addCriterion("COL_17 <>", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17GreaterThan(String value) {
            addCriterion("COL_17 >", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17GreaterThanOrEqualTo(String value) {
            addCriterion("COL_17 >=", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17LessThan(String value) {
            addCriterion("COL_17 <", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17LessThanOrEqualTo(String value) {
            addCriterion("COL_17 <=", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17Like(String value) {
            addCriterion("COL_17 like", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotLike(String value) {
            addCriterion("COL_17 not like", value, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17In(List<String> values) {
            addCriterion("COL_17 in", values, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotIn(List<String> values) {
            addCriterion("COL_17 not in", values, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17Between(String value1, String value2) {
            addCriterion("COL_17 between", value1, value2, "col17");
            return (Criteria) this;
        }

        public Criteria andCol17NotBetween(String value1, String value2) {
            addCriterion("COL_17 not between", value1, value2, "col17");
            return (Criteria) this;
        }

        public Criteria andCol18IsNull() {
            addCriterion("COL_18 is null");
            return (Criteria) this;
        }

        public Criteria andCol18IsNotNull() {
            addCriterion("COL_18 is not null");
            return (Criteria) this;
        }

        public Criteria andCol18EqualTo(String value) {
            addCriterion("COL_18 =", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotEqualTo(String value) {
            addCriterion("COL_18 <>", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18GreaterThan(String value) {
            addCriterion("COL_18 >", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18GreaterThanOrEqualTo(String value) {
            addCriterion("COL_18 >=", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18LessThan(String value) {
            addCriterion("COL_18 <", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18LessThanOrEqualTo(String value) {
            addCriterion("COL_18 <=", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18Like(String value) {
            addCriterion("COL_18 like", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotLike(String value) {
            addCriterion("COL_18 not like", value, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18In(List<String> values) {
            addCriterion("COL_18 in", values, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotIn(List<String> values) {
            addCriterion("COL_18 not in", values, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18Between(String value1, String value2) {
            addCriterion("COL_18 between", value1, value2, "col18");
            return (Criteria) this;
        }

        public Criteria andCol18NotBetween(String value1, String value2) {
            addCriterion("COL_18 not between", value1, value2, "col18");
            return (Criteria) this;
        }

        public Criteria andCol19IsNull() {
            addCriterion("COL_19 is null");
            return (Criteria) this;
        }

        public Criteria andCol19IsNotNull() {
            addCriterion("COL_19 is not null");
            return (Criteria) this;
        }

        public Criteria andCol19EqualTo(String value) {
            addCriterion("COL_19 =", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotEqualTo(String value) {
            addCriterion("COL_19 <>", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19GreaterThan(String value) {
            addCriterion("COL_19 >", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19GreaterThanOrEqualTo(String value) {
            addCriterion("COL_19 >=", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19LessThan(String value) {
            addCriterion("COL_19 <", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19LessThanOrEqualTo(String value) {
            addCriterion("COL_19 <=", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19Like(String value) {
            addCriterion("COL_19 like", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotLike(String value) {
            addCriterion("COL_19 not like", value, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19In(List<String> values) {
            addCriterion("COL_19 in", values, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotIn(List<String> values) {
            addCriterion("COL_19 not in", values, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19Between(String value1, String value2) {
            addCriterion("COL_19 between", value1, value2, "col19");
            return (Criteria) this;
        }

        public Criteria andCol19NotBetween(String value1, String value2) {
            addCriterion("COL_19 not between", value1, value2, "col19");
            return (Criteria) this;
        }

        public Criteria andCol20IsNull() {
            addCriterion("COL_20 is null");
            return (Criteria) this;
        }

        public Criteria andCol20IsNotNull() {
            addCriterion("COL_20 is not null");
            return (Criteria) this;
        }

        public Criteria andCol20EqualTo(Long value) {
            addCriterion("COL_20 =", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotEqualTo(Long value) {
            addCriterion("COL_20 <>", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20GreaterThan(Long value) {
            addCriterion("COL_20 >", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20GreaterThanOrEqualTo(Long value) {
            addCriterion("COL_20 >=", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20LessThan(Long value) {
            addCriterion("COL_20 <", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20LessThanOrEqualTo(Long value) {
            addCriterion("COL_20 <=", value, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20In(List<Long> values) {
            addCriterion("COL_20 in", values, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotIn(List<Long> values) {
            addCriterion("COL_20 not in", values, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20Between(Long value1, Long value2) {
            addCriterion("COL_20 between", value1, value2, "col20");
            return (Criteria) this;
        }

        public Criteria andCol20NotBetween(Long value1, Long value2) {
            addCriterion("COL_20 not between", value1, value2, "col20");
            return (Criteria) this;
        }

        public Criteria andCol21IsNull() {
            addCriterion("COL_21 is null");
            return (Criteria) this;
        }

        public Criteria andCol21IsNotNull() {
            addCriterion("COL_21 is not null");
            return (Criteria) this;
        }

        public Criteria andCol21EqualTo(BigDecimal value) {
            addCriterion("COL_21 =", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotEqualTo(BigDecimal value) {
            addCriterion("COL_21 <>", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21GreaterThan(BigDecimal value) {
            addCriterion("COL_21 >", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("COL_21 >=", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21LessThan(BigDecimal value) {
            addCriterion("COL_21 <", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21LessThanOrEqualTo(BigDecimal value) {
            addCriterion("COL_21 <=", value, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21In(List<BigDecimal> values) {
            addCriterion("COL_21 in", values, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotIn(List<BigDecimal> values) {
            addCriterion("COL_21 not in", values, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("COL_21 between", value1, value2, "col21");
            return (Criteria) this;
        }

        public Criteria andCol21NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("COL_21 not between", value1, value2, "col21");
            return (Criteria) this;
        }

        public Criteria andCol22IsNull() {
            addCriterion("COL_22 is null");
            return (Criteria) this;
        }

        public Criteria andCol22IsNotNull() {
            addCriterion("COL_22 is not null");
            return (Criteria) this;
        }

        public Criteria andCol22EqualTo(Object value) {
            addCriterion("COL_22 =", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotEqualTo(Object value) {
            addCriterion("COL_22 <>", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22GreaterThan(Object value) {
            addCriterion("COL_22 >", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22GreaterThanOrEqualTo(Object value) {
            addCriterion("COL_22 >=", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22LessThan(Object value) {
            addCriterion("COL_22 <", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22LessThanOrEqualTo(Object value) {
            addCriterion("COL_22 <=", value, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22In(List<Object> values) {
            addCriterion("COL_22 in", values, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotIn(List<Object> values) {
            addCriterion("COL_22 not in", values, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22Between(Object value1, Object value2) {
            addCriterion("COL_22 between", value1, value2, "col22");
            return (Criteria) this;
        }

        public Criteria andCol22NotBetween(Object value1, Object value2) {
            addCriterion("COL_22 not between", value1, value2, "col22");
            return (Criteria) this;
        }

        public Criteria andCol23IsNull() {
            addCriterion("COL_23 is null");
            return (Criteria) this;
        }

        public Criteria andCol23IsNotNull() {
            addCriterion("COL_23 is not null");
            return (Criteria) this;
        }

        public Criteria andCol23EqualTo(Object value) {
            addCriterion("COL_23 =", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotEqualTo(Object value) {
            addCriterion("COL_23 <>", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23GreaterThan(Object value) {
            addCriterion("COL_23 >", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23GreaterThanOrEqualTo(Object value) {
            addCriterion("COL_23 >=", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23LessThan(Object value) {
            addCriterion("COL_23 <", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23LessThanOrEqualTo(Object value) {
            addCriterion("COL_23 <=", value, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23In(List<Object> values) {
            addCriterion("COL_23 in", values, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotIn(List<Object> values) {
            addCriterion("COL_23 not in", values, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23Between(Object value1, Object value2) {
            addCriterion("COL_23 between", value1, value2, "col23");
            return (Criteria) this;
        }

        public Criteria andCol23NotBetween(Object value1, Object value2) {
            addCriterion("COL_23 not between", value1, value2, "col23");
            return (Criteria) this;
        }

        public Criteria andCol24IsNull() {
            addCriterion("COL_24 is null");
            return (Criteria) this;
        }

        public Criteria andCol24IsNotNull() {
            addCriterion("COL_24 is not null");
            return (Criteria) this;
        }

        public Criteria andCol24EqualTo(Date value) {
            addCriterion("COL_24 =", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotEqualTo(Date value) {
            addCriterion("COL_24 <>", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24GreaterThan(Date value) {
            addCriterion("COL_24 >", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24GreaterThanOrEqualTo(Date value) {
            addCriterion("COL_24 >=", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24LessThan(Date value) {
            addCriterion("COL_24 <", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24LessThanOrEqualTo(Date value) {
            addCriterion("COL_24 <=", value, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24In(List<Date> values) {
            addCriterion("COL_24 in", values, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotIn(List<Date> values) {
            addCriterion("COL_24 not in", values, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24Between(Date value1, Date value2) {
            addCriterion("COL_24 between", value1, value2, "col24");
            return (Criteria) this;
        }

        public Criteria andCol24NotBetween(Date value1, Date value2) {
            addCriterion("COL_24 not between", value1, value2, "col24");
            return (Criteria) this;
        }

        public Criteria andCol25IsNull() {
            addCriterion("COL_25 is null");
            return (Criteria) this;
        }

        public Criteria andCol25IsNotNull() {
            addCriterion("COL_25 is not null");
            return (Criteria) this;
        }

        public Criteria andCol25EqualTo(Date value) {
            addCriterionForJDBCDate("COL_25 =", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotEqualTo(Date value) {
            addCriterionForJDBCDate("COL_25 <>", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25GreaterThan(Date value) {
            addCriterionForJDBCDate("COL_25 >", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COL_25 >=", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25LessThan(Date value) {
            addCriterionForJDBCDate("COL_25 <", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("COL_25 <=", value, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25In(List<Date> values) {
            addCriterionForJDBCDate("COL_25 in", values, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotIn(List<Date> values) {
            addCriterionForJDBCDate("COL_25 not in", values, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25Between(Date value1, Date value2) {
            addCriterionForJDBCDate("COL_25 between", value1, value2, "col25");
            return (Criteria) this;
        }

        public Criteria andCol25NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("COL_25 not between", value1, value2, "col25");
            return (Criteria) this;
        }

        public Criteria andCol26IsNull() {
            addCriterion("COL_26 is null");
            return (Criteria) this;
        }

        public Criteria andCol26IsNotNull() {
            addCriterion("COL_26 is not null");
            return (Criteria) this;
        }

        public Criteria andCol26EqualTo(Boolean value) {
            addCriterion("COL_26 =", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotEqualTo(Boolean value) {
            addCriterion("COL_26 <>", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26GreaterThan(Boolean value) {
            addCriterion("COL_26 >", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26GreaterThanOrEqualTo(Boolean value) {
            addCriterion("COL_26 >=", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26LessThan(Boolean value) {
            addCriterion("COL_26 <", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26LessThanOrEqualTo(Boolean value) {
            addCriterion("COL_26 <=", value, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26In(List<Boolean> values) {
            addCriterion("COL_26 in", values, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotIn(List<Boolean> values) {
            addCriterion("COL_26 not in", values, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26Between(Boolean value1, Boolean value2) {
            addCriterion("COL_26 between", value1, value2, "col26");
            return (Criteria) this;
        }

        public Criteria andCol26NotBetween(Boolean value1, Boolean value2) {
            addCriterion("COL_26 not between", value1, value2, "col26");
            return (Criteria) this;
        }

        public Criteria andCol29IsNull() {
            addCriterion("COL_29 is null");
            return (Criteria) this;
        }

        public Criteria andCol29IsNotNull() {
            addCriterion("COL_29 is not null");
            return (Criteria) this;
        }

        public Criteria andCol29EqualTo(String value) {
            addCriterion("COL_29 =", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotEqualTo(String value) {
            addCriterion("COL_29 <>", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29GreaterThan(String value) {
            addCriterion("COL_29 >", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29GreaterThanOrEqualTo(String value) {
            addCriterion("COL_29 >=", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29LessThan(String value) {
            addCriterion("COL_29 <", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29LessThanOrEqualTo(String value) {
            addCriterion("COL_29 <=", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29Like(String value) {
            addCriterion("COL_29 like", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotLike(String value) {
            addCriterion("COL_29 not like", value, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29In(List<String> values) {
            addCriterion("COL_29 in", values, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotIn(List<String> values) {
            addCriterion("COL_29 not in", values, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29Between(String value1, String value2) {
            addCriterion("COL_29 between", value1, value2, "col29");
            return (Criteria) this;
        }

        public Criteria andCol29NotBetween(String value1, String value2) {
            addCriterion("COL_29 not between", value1, value2, "col29");
            return (Criteria) this;
        }

        public Criteria andCol30IsNull() {
            addCriterion("COL_30 is null");
            return (Criteria) this;
        }

        public Criteria andCol30IsNotNull() {
            addCriterion("COL_30 is not null");
            return (Criteria) this;
        }

        public Criteria andCol30EqualTo(String value) {
            addCriterion("COL_30 =", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotEqualTo(String value) {
            addCriterion("COL_30 <>", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30GreaterThan(String value) {
            addCriterion("COL_30 >", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30GreaterThanOrEqualTo(String value) {
            addCriterion("COL_30 >=", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30LessThan(String value) {
            addCriterion("COL_30 <", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30LessThanOrEqualTo(String value) {
            addCriterion("COL_30 <=", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30Like(String value) {
            addCriterion("COL_30 like", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotLike(String value) {
            addCriterion("COL_30 not like", value, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30In(List<String> values) {
            addCriterion("COL_30 in", values, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotIn(List<String> values) {
            addCriterion("COL_30 not in", values, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30Between(String value1, String value2) {
            addCriterion("COL_30 between", value1, value2, "col30");
            return (Criteria) this;
        }

        public Criteria andCol30NotBetween(String value1, String value2) {
            addCriterion("COL_30 not between", value1, value2, "col30");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated do_not_delete_during_merge Sun Sep 27 22:16:44 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.TEST_TBL
     *
     * @mbg.generated Sun Sep 27 22:16:44 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}